#!/bin/bash

# reload bashrc
alias vb='vim ~/.bashrc'
alias sb='. ~/.bashrc'

# use nvim when available
if hash nvim 2> /dev/null; then
    alias vim='nvim'
    alias vimdiff='nvim -d'
fi

# common aliases
alias vim='nvim'
alias ll='ls -l'
alias lls='ls -la'
alias t='tmux'
alias c='clear'
alias e='exit'
alias st='storm'
alias h='history'
alias rm='rm -vi'
alias cp='cp -vi'
alias mv='mv -vi'
alias mkdir='mkdir -v'
alias chmod='chmod -v'
alias chgrp='chgrp -v'
alias chown='chown -v'
alias diff='colordiff'
alias open='xdg-open'
alias wide-diff='diff -W $(tput cols)'
alias wide-pr='pr -w $(tput cols) -m -t'
alias ls="ls --color=always"
alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"

# terminal display size
alias lines='tput lines'
alias columns='tput cols'

# which services own which process
alias psc='ps xawf -eo pid,user,cgroup,args'

# run virsh commands without sudo
alias virsh="virsh --connect qemu:///system"

# docker shortcuts
alias dkrm='docker rm $(docker ps -qa)'
alias dkrmi='docker rmi $(docker images -q)'
alias dkvrm='docker volume rm $(docker volume ls -q)'

# vhosts
alias vhosts='sudo vim /etc/hosts'

# directory navigation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# ai
alias update-cursor-cli='curl -fsSL https://cursor.com/install | bash'
alias update-codex='sudo npm install -g @openai/codex@latest'
alias update-claude='claude update'
alias update-copilot='sudo npm install -g @github/copilot@latest'
