#!/bin/bash
# bash wrappers for docker run commands

# docker rm function
docker_rm(){
    local name=$1
    local state
    state=$(docker inspect --format "{{.State.Running}}" "$name" 2>/dev/null)

    if [[ "$state" == "false" ]]
    then
        docker rm "$name"
    fi
}
keepassx(){
    docker_rm keepassx

    xhost + 1> /dev/null
	docker run -d \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /home/$USER/${keepassdb}:/root/${keepassdb} \
    -v /dev/dri/card0:/dev/dri/card0 \
    --name keepassx keepassx
}
mysql-load(){
    docker run -d \
        -e MARIADB_ROOT_PASSWORD=password \
        -v $(pwd)/"$@":/docker-entrypoint-initdb.d \
        --workdir /docker-entrypoint-initdb.d \
        -p 3306:3306 \
        --name mariadb \
        mariadb
}
network-miner(){
    docker_rm network-miner

    docker run -it -d \
        -e DISPLAY=$DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v "$(pwd):/home/networkminer" \
        --name network-miner \
        network-miner
}
postman(){
    docker_rm postman

    docker run -it -d \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /home/$USER/.config/Postman:/home/developer/.config/Postman \
        -e DISPLAY=$DISPLAY \
        --name postman \
        postman
}
splunk(){
    docker run -d \
        -p 8000:8000 \
        -v splunk-etc:/opt/splunk/etc \
        -v splunk-var:/opt/splunk/var \
        -e "SPLUNK_START_ARGS=--accept-license" \
        -e "SPLUNK_PASSWORD=password" \
        --name splunk \
        splunk/splunk:8.2.2
}
virt-manager(){
    docker_rm virt-manager
    
    xhost + 1> /dev/null
    docker run -d \
        -e DISPLAY=$DISPLAY \
        -v /home/$USER/.ssh/known_hosts:/home/virt-manager/.ssh/known_hosts:ro \
        -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
        --net=host \
        --name virt-manager \
        virt-manager
}
# dockerfile linter
dockerlint(){
    docker run --rm -i \
        hadolint/hadolint < "$@"
}
# inspect docker image layers
dockerdive(){
    docker run --rm -it \
        -v /var/run/docker.sock:/var/run/docker.sock \
        wagoodman/dive:latest "$@"
}
signal(){
	docker run -d --rm \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    --net=host \
    -v ${HOME}/.config/Signal:/root/.config/Signal \
    --name signal signal
}
