#!/bin/bash

# set default text editor
export EDITOR=vim
export VISUAL=vim

# bash history
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export HISTFILESIZE=100000
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE='ll:cd ..:t:sb:cd:vb:cd -'

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# bcrc
export BC_ENV_ARGS=$HOME/.bcrc
