#!/bin/bash

# set default text editor
if hash nvim 2> /dev/null; then
    export EDITOR=nvim
    export VISUAL=nvim
else
    export EDITOR=vim
    export VISUAL=vim
fi

# bash history
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export HISTFILESIZE=100000
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE='ll:cd ..:t:sb:cd:vb:cd -'

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# bcrc
export BC_ENV_ARGS=$HOME/.bcrc
