#!/bin/sh

# add local bin home path
export PATH="${HOME}/.local/bin:${PATH}"

# add local scripts home path
export PATH="${HOME}/.local/scripts:${PATH}"

# Homebrew
#export PATH="/opt/homebrew/bin:${PATH}"
#export PATH="/opt/homebrew/sbin:${PATH}"

# Remove duplicate $PATH entries
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
